package com.mps.parkingservice.service;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.mockito.junit.jupiter.MockitoSettings;
import org.mockito.quality.Strictness;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.when;

/**
 * A lot of boilerplate unit tests
 * Generated by AI
 */
@ExtendWith(MockitoExtension.class)
@MockitoSettings(strictness = Strictness.LENIENT)
class PriceCalculationServiceTest {

    private static final int DEFAULT_EXTRA_CHARGE_AMOUNT = 1;
    private static final int DEFAULT_EXTRA_CHARGE_TIME = 5;
    private static final int HIGH_EXTRA_CHARGE_AMOUNT = 5;
    private static final int ZERO_EXTRA_CHARGE_TIME = 0;
    private static final int ZERO_EXTRA_CHARGE_AMOUNT = 0;

    private static final double DEFAULT_RATE_TYPE_1 = 0.1;
    private static final double DEFAULT_RATE_TYPE_2 = 0.2;
    private static final double DEFAULT_RATE_TYPE_3 = 0.4;

    private static final int VEHICLE_TYPE_SMALL = 1;
    private static final int VEHICLE_TYPE_MEDIUM = 2;
    private static final int VEHICLE_TYPE_LARGE = 3;
    private static final int INVALID_VEHICLE_TYPE_0 = 0;
    private static final int INVALID_VEHICLE_TYPE_4 = 4;
    private static final int INVALID_VEHICLE_TYPE_NEGATIVE = -1;

    private static final int MINUTES_0 = 0;
    private static final int MINUTES_1 = 1;
    private static final int MINUTES_3 = 3;
    private static final int MINUTES_7 = 7;
    private static final int MINUTES_10 = 10;
    private static final int MINUTES_30 = 30;
    private static final int MINUTES_60 = 60;

    private static final double PRICE_DELTA = 0.0001;

    @Mock
    private ParkingConfigService parkingConfigService;

    private PriceCalculationService priceCalculationService;

    @BeforeEach
    void setUp() {
        priceCalculationService = new PriceCalculationService(parkingConfigService);
        stubConfig(DEFAULT_EXTRA_CHARGE_AMOUNT, DEFAULT_EXTRA_CHARGE_TIME);
    }

    private void stubConfig(int extraChargeAmount, int extraChargeTimeInMinutes) {
        when(parkingConfigService.getExtraChargeAmountGbp()).thenReturn(extraChargeAmount);
        when(parkingConfigService.getExtraChargeTimeMin()).thenReturn(extraChargeTimeInMinutes);
        when(parkingConfigService.getRateType1()).thenReturn(DEFAULT_RATE_TYPE_1);
        when(parkingConfigService.getRateType2()).thenReturn(DEFAULT_RATE_TYPE_2);
        when(parkingConfigService.getRateType3()).thenReturn(DEFAULT_RATE_TYPE_3);
    }

    @Nested
    class CalculatePriceForSmallCar {

        @Test
        void shouldCalculateCorrectly_when10MinutesParked() {
            // rate=0.1, extraPay=1*10/5=2 → 0.1*10 + 2 = 3.0
            double price = priceCalculationService.calculatePrice(MINUTES_10, VEHICLE_TYPE_SMALL);
            assertEquals(3.0, price);
        }

        @Test
        void shouldCalculateCorrectly_when30MinutesParked() {
            // rate=0.1, extraPay=1*30/5=6 → 0.1*30 + 6 = 9.0
            double price = priceCalculationService.calculatePrice(MINUTES_30, VEHICLE_TYPE_SMALL);
            assertEquals(9.0, price);
        }

        @Test
        void shouldCalculateCorrectly_when60MinutesParked() {
            // rate=0.1, extraPay=1*60/5=12 → 0.1*60 + 12 = 18.0
            double price = priceCalculationService.calculatePrice(MINUTES_60, VEHICLE_TYPE_SMALL);
            assertEquals(18.0, price);
        }
    }

    @Nested
    class CalculatePriceForMediumCar {

        @Test
        void shouldCalculateCorrectly_when10MinutesParked() {
            // rate=0.2, extraPay=1*10/5=2 → 0.2*10 + 2 = 4.0
            double price = priceCalculationService.calculatePrice(MINUTES_10, VEHICLE_TYPE_MEDIUM);
            assertEquals(4.0, price);
        }

        @Test
        void shouldCalculateCorrectly_when30MinutesParked() {
            // rate=0.2, extraPay=1*30/5=6 → 0.2*30 + 6 = 12.0
            double price = priceCalculationService.calculatePrice(MINUTES_30, VEHICLE_TYPE_MEDIUM);
            assertEquals(12.0, price);
        }
    }

    @Nested
    class CalculatePriceForLargeCar {

        @Test
        void shouldCalculateCorrectly_when10MinutesParked() {
            // rate=0.4, extraPay=1*10/5=2 → 0.4*10 + 2 = 6.0
            double price = priceCalculationService.calculatePrice(MINUTES_10, VEHICLE_TYPE_LARGE);
            assertEquals(6.0, price);
        }

        @Test
        void shouldCalculateCorrectly_when60MinutesParked() {
            // rate=0.4, extraPay=1*60/5=12 → 0.4*60 + 12 = 36.0
            double price = priceCalculationService.calculatePrice(MINUTES_60, VEHICLE_TYPE_LARGE);
            assertEquals(36.0, price);
        }
    }

    @Nested
    class InvalidVehicleType {

        @Test
        void shouldThrowException_whenVehicleTypeIs0() {
            assertThrows(IllegalArgumentException.class,
                    () -> priceCalculationService.calculatePrice(MINUTES_10, INVALID_VEHICLE_TYPE_0));
        }

        @Test
        void shouldThrowException_whenVehicleTypeIs4() {
            assertThrows(IllegalArgumentException.class,
                    () -> priceCalculationService.calculatePrice(MINUTES_10, INVALID_VEHICLE_TYPE_4));
        }

        @Test
        void shouldThrowException_whenVehicleTypeIsNegative() {
            assertThrows(IllegalArgumentException.class,
                    () -> priceCalculationService.calculatePrice(MINUTES_10, INVALID_VEHICLE_TYPE_NEGATIVE));
        }
    }

    @Nested
    class EdgeCases {

        @Test
        void shouldReturnZero_whenZeroMinutesParked() {
            double price = priceCalculationService.calculatePrice(MINUTES_0, VEHICLE_TYPE_SMALL);
            assertEquals(0.0, price);
        }

        @Test
        void shouldTruncateExtraPay_whenMinutesNotDivisibleByChargeTime() {
            // rate=0.1, extraPay=1*3/5=0 (integer division) → 0.1*3 + 0 = 0.3
            double price = priceCalculationService.calculatePrice(MINUTES_3, VEHICLE_TYPE_SMALL);
            assertEquals(0.3, price, PRICE_DELTA);
        }

        @Test
        void shouldTruncateExtraPay_when7MinutesParked() {
            // rate=0.1, extraPay=1*7/5=1 (integer division) → 0.1*7 + 1 = 1.7
            double price = priceCalculationService.calculatePrice(MINUTES_7, VEHICLE_TYPE_SMALL);
            assertEquals(1.7, price, PRICE_DELTA);
        }

        @Test
        void shouldCalculateCorrectly_when1MinuteParked() {
            // rate=0.1, extraPay=1*1/5=0 (integer division) → 0.1*1 + 0 = 0.1
            double price = priceCalculationService.calculatePrice(MINUTES_1, VEHICLE_TYPE_SMALL);
            assertEquals(0.1, price, PRICE_DELTA);
        }
    }

    @Nested
    class DifferentExtraChargeConfig {

        @Test
        void shouldApplyHigherExtraCharge_whenAmountIs5() {
            stubConfig(HIGH_EXTRA_CHARGE_AMOUNT, DEFAULT_EXTRA_CHARGE_TIME);
            // rate=0.1, extraPay=5*10/5=10 → 0.1*10 + 10 = 11.0
            double price = priceCalculationService.calculatePrice(MINUTES_10, VEHICLE_TYPE_SMALL);
            assertEquals(11.0, price);
        }

        @Test
        void shouldApplyNoExtraCharge_whenChargeTimeIsZero() {
            stubConfig(DEFAULT_EXTRA_CHARGE_AMOUNT, ZERO_EXTRA_CHARGE_TIME);
            // extraChargeTimeInMinutes=0 → extraPay=0 → 0.2*10 = 2.0
            double price = priceCalculationService.calculatePrice(MINUTES_10, VEHICLE_TYPE_MEDIUM);
            assertEquals(2.0, price);
        }

        @Test
        void shouldApplyNoExtraCharge_whenAmountIsZero() {
            stubConfig(ZERO_EXTRA_CHARGE_AMOUNT, DEFAULT_EXTRA_CHARGE_TIME);
            // extraPay=0*10/5=0 → 0.1*10 + 0 = 1.0
            double price = priceCalculationService.calculatePrice(MINUTES_10, VEHICLE_TYPE_SMALL);
            assertEquals(1.0, price);
        }
    }
}